### ISSUE TITLE
0.4.0

### ISSUE THREAD

**Issue by nicoddemus** [conda-forge/colorama-feedstock#10]
Hmm [0.4.0](https://pypi.org/project/colorama/0.4.0/#files) was released on 2018-10-10 but the bot did not open a PR yet to update the version. Any idea why?

**Comment by ocefpaf** [comment]
The source URL changed from `.tar.gz` to `.zip` :unamused: 

We can probably make that a little bit more robust by using PyPI's metadata.

**Comment by nicoddemus** [comment]
Ahh I see, thanks!
